//admin
export const FETCH_ALL_POSTS = 'FETCH_ALL_POSTS';
export const FETCH_ALL_POSTS_NO_PAGINATE = 'FETCH_ALL_POSTS_NO_PAGINATE';
export const FETCH_BY_SEARCH = 'FETCH_BY_SEARCH';
export const FETCH_POST = 'FETCH_POST';
export const FETCH_RECOMMEND_POSTS = 'FETCH_RECOMMEND_POSTS';

export const CREATE_POST = 'CREATE_POST';
export const UPDATE_POST = 'UPDATE_POST';
export const DELETE_POST = 'DELETE_POST';
export const LIKE_POST = 'LIKE_POST';
export const COMMENT_POST = 'COMMENT_POST';

export const START_LOADING = 'START_LOADING';
export const END_LOADING = 'END_LOADING';

//Admin
export const AUTH_ADMIN = 'AUTH_ADMIN';
export const LOGOUT_ADMIN = 'LOGOUT_ADMIN';

export const FETCH_ALL_ADMINS = 'FETCH_ALL_ADMINS';
export const FETCH_ADMINS_BY_SEARCH = 'FETCH_ADMINS_BY_SEARCH';

export const FETCH_ALL_USERS = 'FETCH_ALL_USERS';
export const FETCH_USERS_BY_SEARCH = 'FETCH_USERS_BY_SEARCH';
export const DELETE_USER = 'DELETE_USER';

//User
export const AUTH_USER = 'AUTH_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

export const FETCH_USER = 'FETCH_USER';
export const UPDATE_USER = 'UPDATE_USER';
